- name: upgrade packages and reboot (if necessary)
  hosts: all
  become: yes
  become_method: sudo

  tasks: # tasks are done in order

    # do an "apt-get update", to ensure latest package lists
    - name: apt-get update
      apt:
        update-cache: yes

    # get a list of packages that have updates
    - name: get list of pending upgrades
      command: apt-get --simulate dist-upgrade
      args:
        warn: false # don't warn us about apt having its own plugin
      register: apt_simulate

    # pick out list of pending updates from command output
    - name: parse apt-get output to get list of changed packages
      set_fact:
        security_updates: '{{ apt_simulate.stdout_lines | select("match", "^Inst.*security") | list | length }}'
        updates: '{{ apt_simulate.stdout_lines | select("match", "^Inst((?!security).)*$") | list |length }}'
        cacheable: true

    # tell user about packages being updated
    - name: show pending updates
      debug:
        var: updates,security_updates
      when: updates.0 is defined
    - name: fail if security updates 
      fail:
        msg: "The system may not be provisioned according to the CMDB status."
      when: security_updates != "0"
